################################################################################
# DIGITAL KARYOTYPING PIPELINE - PARAMETER TEMPLATE
# Copy this file and fill in your project-specific paths
################################################################################

# Reference Genome (switch between GRCh37 or GRCh38 for human reference genome)

PAR: datasets/PAR/PAR_Coord_GRCh38.txt
# PAR: datasets/PAR/PAR_Coord_GRCh37.txt

fasta: <path_to_Homo_sapiens.GRCh38.dna.primary_assembly.fa>
# fasta: <path_to_Homo_sapiens.GRCh37.dna.primary_assembly.fa>

########################################################

# Project Information
project_ID: 'YOUR_PROJECT_ID'
responsible_person: 'Name_of_the_requester'

########################################################

# Sample Pairing File (TSV/XLS with 'Sample' and 'Reference' columns).
# Ensure to run preprocessing/preprocessing_run.sh to generate the sample pairing file in xls format 
samples_refs: /Path/to/pipeline_digital_karyotyping/sample_sheet.xls


########################################################

manifest: /Path/to/data/GSA-MD-48v4-0_Manifest_Files/<Manifest_File>.csv  # Illumina Manifest (CSV format from Illumina).

fullTable: /Path/to/data/<Full_Data_Table>.txt  # GenomeStudio Export Files
samplesTable: /Path/to/data/<Samples_Table>.txt # GenomeStudio Export Files
snpTable: /Path/to/data/<SNP_Table>.txt # GenomeStudio Export Files
gsplink: /Path/to/data/GS/<GS_File>/PLINK_<Date>_<Time> # PLINK Files (directory containing .ped and .map)

########################################################

# Output Directory (optional - can also use --outdir flag)

# outdir: 'path/to/results/'


########################################################


 

 

  